services:
  db:
    image: postgres:16
    container_name: todo_postgres
    restart: always
    env_file:
      - .envs/.env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    restart: always
    depends_on:
      - db
    env_file:
      - .envs/.env.app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  pgdata:
